### ISSUE TITLE
Correzione colore Tessere + tabellone 

### ISSUE THREAD

**Issue by AsiaLeoneCvr** [Cmod777/MONOPOLY-BITCOIN-EDITION#1]
Per Santorini, Positano e Capri nelle schede e nel tabellone cambierei il colore ( arancione su arancione non si legge bene nel tabellone)

Potresti usare questo: https://rgb.to/color/11655/marrone-scuro

**Comment by Cmod777** [comment]
Si, la sfumatura diversa di arancione in effetti non rende bene. Prima di utilizzare un altro colore (il marrone andrebbe anche bene) prova a vedere se si puó usare un colore di quelli scelti nella Palette ufficiale di "Ventuno Italia"

**Comment by AsiaLeoneCvr** [comment]
> Si, la sfumatura diversa di arancione in effetti non rende bene. Prima di utilizzare un altro colore (il marrone andrebbe anche bene) prova a vedere se si puó usare un colore di quelli scelti nella Palette ufficiale di "Ventuno Italia"

Ho dato un'occhiata, ma non penso nessuno possa essere più leggibile. 
Tulip andrebbe bene, ma si confondrebbe con St moriz e gli altri viola. 
![photo_2022-12-14 16 53 12](https://user-images.githubusercontent.com/116765782/207644212-41b146e4-a183-4802-8723-4772f58f7997.jpeg)

**Comment by Cmod777** [comment]
Allora vada per marrone :)

**Comment by Cmod777** [comment]
SOSTITUZIONE FILE - NUOVA CARTELLA
fixati errori issue, aggiunta nota variante di gioco con quantità di sats inferiore, trasformazione regolamento da png a pdf (colore corretto come da suggerimento)
