### ISSUE TITLE
Correzione Testo su regolamento

### ISSUE THREAD

**Issue by AsiaLeoneCvr** [Cmod777/MONOPOLY-BITCOIN-EDITION#2]
1)Sostituire soldi con sats

![Screenshot 2022-12-14 at 16 04 46](https://user-images.githubusercontent.com/116765782/207640077-8f8931a3-ed2f-4e41-912c-b7727643c0f2.png)

2) Ho inteso male io il testo o sarebbe meglio" **vi** sfidate"?
![Screenshot 2022-12-14 at 15 54 20](https://user-images.githubusercontent.com/116765782/207640356-77875b3e-d0a1-4392-82d3-1969f663c105.png)

**Comment by Cmod777** [comment]
1) ok
2) si, errore di battitura

**Comment by Cmod777** [comment]
SOSTITUZIONE FILE - NUOVA CARTELLA
fixati errori issue, aggiunta nota variante di gioco con quantità di sats inferiore, trasformazione regolamento da png a pdf
(ho dimenticato di sostituire "soldi" con "sats", includerò il fix in caso di nuove segnalazioni, effettivamente i sats sono soldi, è giusto iniziare a dimenticarsi completamente che esistano le valute fiat LOL)
